CREATE OR REPLACE TASK RISK_DB.RAW.RISK_DATA_INGEST_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('RISK_DB.RAW.RISK_DATA_STAGE_STREAM')
AS
  CALL RISK_DB.RAW.LOAD_NEW_CSV_FILES();

-- Resume the task after creation
ALTER TASK RISK_DB.RAW.RISK_DATA_INGEST_TASK RESUME;
