CREATE OR REPLACE PROCEDURE RISK_DB.CURATED.SP_LOAD_REF_POLICY_DOCUMENTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO RISK_DB.CURATED.REF_POLICY_DOCUMENTS tgt
    USING RISK_DB.CURATED.INT_POLICY_DOCUMENTS src
    ON tgt.POLICY_ID = src.POLICY_ID
    WHEN MATCHED AND (
        tgt.POLICY_NAME != src.POLICY_NAME OR
        tgt.CLASSIFICATION != src.CLASSIFICATION OR
        COALESCE(TO_CHAR(tgt.GENERATED_AT), '') != COALESCE(TO_CHAR(src.GENERATED_AT), '') OR
        COALESCE(tgt.PURPOSE, '') != COALESCE(src.PURPOSE, '') OR
        COALESCE(tgt.VIOLATIONS, '') != COALESCE(src.VIOLATIONS, '')
    ) THEN UPDATE SET
        tgt.POLICY_NAME = src.POLICY_NAME,
        tgt.CLASSIFICATION = src.CLASSIFICATION,
        tgt.GENERATED_AT = src.GENERATED_AT,
        tgt.PURPOSE = src.PURPOSE,
        tgt.VIOLATIONS = src.VIOLATIONS,
        tgt.FULL_CONTENT = src.FULL_CONTENT,
        tgt.CONTENT_LENGTH_CHARS = src.CONTENT_LENGTH_CHARS,
        tgt._LOADED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        POLICY_ID, POLICY_NAME, CLASSIFICATION, GENERATED_AT,
        PURPOSE, VIOLATIONS, FULL_CONTENT, CONTENT_LENGTH_CHARS
    ) VALUES (
        src.POLICY_ID, src.POLICY_NAME, src.CLASSIFICATION, src.GENERATED_AT,
        src.PURPOSE, src.VIOLATIONS, src.FULL_CONTENT, src.CONTENT_LENGTH_CHARS
    );

    RETURN 'REF_POLICY_DOCUMENTS loaded successfully';
END;
$$;
