CREATE OR REPLACE PROCEDURE RISK_DB.CURATED.SP_LOAD_FCT_DEPOSIT_BALANCE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO RISK_DB.CURATED.FCT_DEPOSIT_BALANCE (
        DEPOSIT_ID, DIM_ACCOUNT_SK, DIM_CUSTOMER_SK,
        EFFECTIVE_DATE_SK, MATURITY_DATE_SK,
        DEPOSIT_TYPE, BALANCE, CURRENCY, EFFECTIVE_DATE, MATURITY_DATE,
        INTEREST_RATE, INSURED_AMOUNT, UNINSURED_AMOUNT, STABILITY_FACTOR,
        RUN_OFF_FACTOR, LCR_CATEGORY, NSFR_CATEGORY,
        HAS_CONCENTRATION_RISK, IS_LARGE_DEPOSIT, HAS_LIQUIDITY_VIOLATION,
        DEPOSIT_TERM_DAYS, UNINSURED_RATIO
    )
    SELECT
        src.DEPOSIT_ID,
        da.DIM_ACCOUNT_SK,
        dc.DIM_CUSTOMER_SK,
        TO_NUMBER(TO_CHAR(src.EFFECTIVE_DATE, 'YYYYMMDD')),
        CASE WHEN src.MATURITY_DATE IS NOT NULL
             THEN TO_NUMBER(TO_CHAR(src.MATURITY_DATE, 'YYYYMMDD'))
             ELSE NULL END,
        src.DEPOSIT_TYPE,
        src.BALANCE,
        src.CURRENCY,
        src.EFFECTIVE_DATE,
        src.MATURITY_DATE,
        src.INTEREST_RATE,
        src.INSURED_AMOUNT,
        src.UNINSURED_AMOUNT,
        src.STABILITY_FACTOR,
        src.RUN_OFF_FACTOR,
        src.LCR_CATEGORY,
        src.NSFR_CATEGORY,
        src.HAS_CONCENTRATION_RISK,
        src.IS_LARGE_DEPOSIT,
        src.HAS_LIQUIDITY_VIOLATION,
        src.DEPOSIT_TERM_DAYS,
        src.UNINSURED_RATIO
    FROM RISK_DB.CURATED.INT_DEPOSIT_BALANCE src
    LEFT JOIN RISK_DB.CURATED.DIM_ACCOUNT da
        ON da.ACCOUNT_ID = src.ACCOUNT_ID AND da.IS_CURRENT = TRUE
    LEFT JOIN RISK_DB.CURATED.DIM_CUSTOMER dc
        ON dc.CUSTOMER_ID = src.CUSTOMER_ID AND dc.IS_CURRENT = TRUE
    WHERE NOT EXISTS (
        SELECT 1 FROM RISK_DB.CURATED.FCT_DEPOSIT_BALANCE tgt
        WHERE tgt.DEPOSIT_ID = src.DEPOSIT_ID
    );

    RETURN 'FCT_DEPOSIT_BALANCE loaded successfully';
END;
$$;
