CREATE OR REPLACE PROCEDURE RISK_DB.CURATED.SP_LOAD_FCT_TRANSACTION()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO RISK_DB.CURATED.FCT_TRANSACTION (
        TRANSACTION_ID, DIM_ACCOUNT_SK, DIM_CUSTOMER_SK, TRANSACTION_DATE_SK,
        TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TIMESTAMP,
        TRANSACTION_TYPE, AMOUNT, CURRENCY, DIRECTION, CHANNEL,
        ORIGINATOR_NAME, ORIGINATOR_COUNTRY, BENEFICIARY_NAME, BENEFICIARY_COUNTRY,
        BENEFICIARY_BANK, PURPOSE_CODE, HAS_AML_FLAG, AML_ALERT_TYPE, RISK_SCORE,
        SCREENING_STATUS, IS_CASH, IS_CTR_FILED, IS_CROSS_BORDER, IS_LARGE_TRANSACTION
    )
    SELECT
        src.TRANSACTION_ID,
        da.DIM_ACCOUNT_SK,
        dc.DIM_CUSTOMER_SK,
        TO_NUMBER(TO_CHAR(src.TRANSACTION_DATE, 'YYYYMMDD')),
        src.TRANSACTION_DATE,
        src.TRANSACTION_TIME,
        src.TRANSACTION_TIMESTAMP,
        src.TRANSACTION_TYPE,
        src.AMOUNT,
        src.CURRENCY,
        src.DIRECTION,
        src.CHANNEL,
        src.ORIGINATOR_NAME,
        src.ORIGINATOR_COUNTRY,
        src.BENEFICIARY_NAME,
        src.BENEFICIARY_COUNTRY,
        src.BENEFICIARY_BANK,
        src.PURPOSE_CODE,
        src.HAS_AML_FLAG,
        src.AML_ALERT_TYPE,
        src.RISK_SCORE,
        src.SCREENING_STATUS,
        src.IS_CASH,
        src.IS_CTR_FILED,
        src.IS_CROSS_BORDER,
        src.IS_LARGE_TRANSACTION
    FROM RISK_DB.CURATED.INT_TRANSACTION src
    LEFT JOIN RISK_DB.CURATED.DIM_ACCOUNT da
        ON da.ACCOUNT_ID = src.ACCOUNT_ID AND da.IS_CURRENT = TRUE
    LEFT JOIN RISK_DB.CURATED.DIM_CUSTOMER dc
        ON dc.CUSTOMER_ID = src.CUSTOMER_ID AND dc.IS_CURRENT = TRUE
    WHERE NOT EXISTS (
        SELECT 1 FROM RISK_DB.CURATED.FCT_TRANSACTION tgt
        WHERE tgt.TRANSACTION_ID = src.TRANSACTION_ID
    );

    RETURN 'FCT_TRANSACTION loaded successfully';
END;
$$;
