CREATE OR REPLACE PROCEDURE RISK_DB.CURATED.SP_LOAD_FCT_LOAN_PERFORMANCE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO RISK_DB.CURATED.FCT_LOAN_PERFORMANCE (
        PERFORMANCE_ID, DIM_LOAN_SK, DIM_CUSTOMER_SK, REPORT_DATE_SK,
        REPORT_DATE, DAYS_PAST_DUE, DELINQUENCY_STATUS,
        PAYMENT_AMOUNT_DUE, PAYMENT_AMOUNT_RECEIVED, OUTSTANDING_PRINCIPAL,
        ACCRUED_INTEREST, PROVISION_AMOUNT, STAGE_IFRS9, ECL_AMOUNT,
        IS_RESTRUCTURED, IS_WRITTEN_OFF, RECOVERY_AMOUNT, RISK_MIGRATION,
        IS_DELINQUENT, PAYMENT_VARIANCE, PAYMENT_COVERAGE_RATIO
    )
    SELECT
        src.PERFORMANCE_ID,
        dl.DIM_LOAN_SK,
        dc.DIM_CUSTOMER_SK,
        TO_NUMBER(TO_CHAR(src.REPORT_DATE, 'YYYYMMDD')),
        src.REPORT_DATE,
        src.DAYS_PAST_DUE,
        src.DELINQUENCY_STATUS,
        src.PAYMENT_AMOUNT_DUE,
        src.PAYMENT_AMOUNT_RECEIVED,
        src.OUTSTANDING_PRINCIPAL,
        src.ACCRUED_INTEREST,
        src.PROVISION_AMOUNT,
        src.STAGE_IFRS9,
        src.ECL_AMOUNT,
        src.IS_RESTRUCTURED,
        src.IS_WRITTEN_OFF,
        src.RECOVERY_AMOUNT,
        src.RISK_MIGRATION,
        src.IS_DELINQUENT,
        src.PAYMENT_VARIANCE,
        src.PAYMENT_COVERAGE_RATIO
    FROM RISK_DB.CURATED.INT_LOAN_PERFORMANCE src
    LEFT JOIN RISK_DB.CURATED.DIM_LOAN dl
        ON dl.LOAN_ID = src.LOAN_ID AND dl.IS_CURRENT = TRUE
    LEFT JOIN RISK_DB.CURATED.DIM_CUSTOMER dc
        ON dc.CUSTOMER_ID = src.CUSTOMER_ID AND dc.IS_CURRENT = TRUE
    WHERE NOT EXISTS (
        SELECT 1 FROM RISK_DB.CURATED.FCT_LOAN_PERFORMANCE tgt
        WHERE tgt.PERFORMANCE_ID = src.PERFORMANCE_ID
    );

    RETURN 'FCT_LOAN_PERFORMANCE loaded successfully';
END;
$$;
