CREATE OR REPLACE PROCEDURE RISK_DB.CURATED.SP_REFRESH_CURATED_LAYER()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Step 1: Load all dimensions first (SCD2)
    CALL RISK_DB.CURATED.SP_LOAD_DIM_CUSTOMER();
    CALL RISK_DB.CURATED.SP_LOAD_DIM_ACCOUNT();
    CALL RISK_DB.CURATED.SP_LOAD_DIM_LOAN();
    CALL RISK_DB.CURATED.SP_LOAD_DIM_PEP();
    CALL RISK_DB.CURATED.SP_LOAD_DIM_SANCTIONS();

    -- Step 2: Load facts (depend on dimension surrogate keys)
    CALL RISK_DB.CURATED.SP_LOAD_FCT_TRANSACTION();
    CALL RISK_DB.CURATED.SP_LOAD_FCT_LOAN_PERFORMANCE();
    CALL RISK_DB.CURATED.SP_LOAD_FCT_DEPOSIT_BALANCE();

    -- Step 3: Load reference table
    CALL RISK_DB.CURATED.SP_LOAD_REF_POLICY_DOCUMENTS();

    RETURN 'Curated layer refresh completed successfully';
END;
$$;
