CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_POLICY_DOCUMENTS AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY POLICY_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.POLICY_DOCUMENTS
    WHERE POLICY_ID IS NOT NULL
)
SELECT
    POLICY_ID,
    TRIM(POLICY_NAME) AS POLICY_NAME,
    UPPER(TRIM(CLASSIFICATION)) AS CLASSIFICATION,
    TRY_TO_TIMESTAMP(GENERATED_DATE, 'YYYYMMDD_HH24MISS') AS GENERATED_AT,
    TRIM(PURPOSE) AS PURPOSE,
    TRIM(VIOLATIONS) AS VIOLATIONS,
    FULL_CONTENT,
    LENGTH(FULL_CONTENT) AS CONTENT_LENGTH_CHARS
FROM deduped
WHERE _rn = 1;
