CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_ACCOUNT AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.ACCOUNT_MASTER
    WHERE ACCOUNT_ID IS NOT NULL
)
SELECT
    TRIM(ACCOUNT_ID) AS ACCOUNT_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    UPPER(TRIM(ACCOUNT_TYPE)) AS ACCOUNT_TYPE,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    OPENING_DATE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPPER(TRIM(BRANCH_CODE)) AS BRANCH_CODE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    COALESCE(BALANCE, 0) AS BALANCE,
    COALESCE(CREDIT_LIMIT, 0) AS CREDIT_LIMIT,
    COALESCE(OVERDRAFT_LIMIT, 0) AS OVERDRAFT_LIMIT,
    LAST_ACTIVITY_DATE,
    COALESCE(RISK_SCORE, 0) AS RISK_SCORE,
    DATEDIFF('day', LAST_ACTIVITY_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_ACTIVITY,
    CASE WHEN DATEDIFF('day', LAST_ACTIVITY_DATE, CURRENT_DATE()) > 90 THEN TRUE ELSE FALSE END AS IS_DORMANT,
    CASE WHEN BALANCE < 0 THEN TRUE ELSE FALSE END AS IS_OVERDRAWN
FROM deduped
WHERE _rn = 1;
