CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_CUSTOMER AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.CUSTOMER_MASTER
    WHERE CUSTOMER_ID IS NOT NULL
)
SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    TRIM(FULL_NAME) AS FULL_NAME,
    DATE_OF_BIRTH,
    UPPER(TRIM(NATIONALITY)) AS NATIONALITY,
    UPPER(TRIM(COUNTRY_OF_RESIDENCE)) AS COUNTRY_OF_RESIDENCE,
    UPPER(TRIM(CUSTOMER_TYPE)) AS CUSTOMER_TYPE,
    UPPER(TRIM(INDUSTRY)) AS INDUSTRY,
    UPPER(TRIM(RISK_RATING)) AS RISK_RATING,
    UPPER(TRIM(KYC_STATUS)) AS KYC_STATUS,
    KYC_LAST_REVIEWED,
    ONBOARDING_DATE,
    COALESCE(PEP_FLAG, FALSE) AS PEP_FLAG,
    COALESCE(SANCTIONS_MATCH_FLAG, FALSE) AS SANCTIONS_MATCH_FLAG,
    ANNUAL_INCOME,
    UPPER(TRIM(SOURCE_OF_FUNDS)) AS SOURCE_OF_FUNDS,
    UPPER(TRIM(ACCOUNT_PURPOSE)) AS ACCOUNT_PURPOSE,
    UPPER(TRIM(STATUS)) AS STATUS,
    CASE WHEN PEP_FLAG = TRUE OR SANCTIONS_MATCH_FLAG = TRUE OR UPPER(TRIM(RISK_RATING)) = 'HIGH'
         THEN TRUE ELSE FALSE END AS IS_HIGH_RISK,
    DATEDIFF('year', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE_YEARS,
    DATEDIFF('day', ONBOARDING_DATE, CURRENT_DATE()) AS DAYS_SINCE_ONBOARDING
FROM deduped
WHERE _rn = 1;
