CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_LOAN_PERFORMANCE AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY PERFORMANCE_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.LOAN_PERFORMANCE
    WHERE PERFORMANCE_ID IS NOT NULL
)
SELECT
    TRIM(PERFORMANCE_ID) AS PERFORMANCE_ID,
    TRIM(LOAN_ID) AS LOAN_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    REPORT_DATE,
    COALESCE(DAYS_PAST_DUE, 0) AS DAYS_PAST_DUE,
    UPPER(TRIM(DELINQUENCY_STATUS)) AS DELINQUENCY_STATUS,
    COALESCE(PAYMENT_AMOUNT_DUE, 0) AS PAYMENT_AMOUNT_DUE,
    COALESCE(PAYMENT_AMOUNT_RECEIVED, 0) AS PAYMENT_AMOUNT_RECEIVED,
    COALESCE(OUTSTANDING_PRINCIPAL, 0) AS OUTSTANDING_PRINCIPAL,
    COALESCE(ACCRUED_INTEREST, 0) AS ACCRUED_INTEREST,
    COALESCE(PROVISION_AMOUNT, 0) AS PROVISION_AMOUNT,
    UPPER(TRIM(STAGE_IFRS9)) AS STAGE_IFRS9,
    COALESCE(ECL_AMOUNT, 0) AS ECL_AMOUNT,
    (RESTRUCTURED_FLAG = 'Y') AS IS_RESTRUCTURED,
    (WRITE_OFF_FLAG = 'Y') AS IS_WRITTEN_OFF,
    COALESCE(RECOVERY_AMOUNT, 0) AS RECOVERY_AMOUNT,
    UPPER(TRIM(RISK_MIGRATION)) AS RISK_MIGRATION,
    CASE WHEN DAYS_PAST_DUE > 0 THEN TRUE ELSE FALSE END AS IS_DELINQUENT,
    (PAYMENT_AMOUNT_RECEIVED - PAYMENT_AMOUNT_DUE) AS PAYMENT_VARIANCE,
    CASE WHEN PAYMENT_AMOUNT_DUE > 0
         THEN ROUND(PAYMENT_AMOUNT_RECEIVED / PAYMENT_AMOUNT_DUE, 4)
         ELSE NULL END AS PAYMENT_COVERAGE_RATIO
FROM deduped
WHERE _rn = 1;
