CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_DEPOSIT_BALANCE AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY DEPOSIT_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.DEPOSIT_BALANCES
    WHERE DEPOSIT_ID IS NOT NULL
)
SELECT
    TRIM(DEPOSIT_ID) AS DEPOSIT_ID,
    TRIM(ACCOUNT_ID) AS ACCOUNT_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    UPPER(TRIM(DEPOSIT_TYPE)) AS DEPOSIT_TYPE,
    COALESCE(BALANCE, 0) AS BALANCE,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    EFFECTIVE_DATE,
    TRY_TO_DATE(MATURITY_DATE) AS MATURITY_DATE,
    INTEREST_RATE,
    COALESCE(INSURED_AMOUNT, 0) AS INSURED_AMOUNT,
    COALESCE(UNINSURED_AMOUNT, 0) AS UNINSURED_AMOUNT,
    STABILITY_FACTOR,
    RUN_OFF_FACTOR,
    UPPER(TRIM(LCR_CATEGORY)) AS LCR_CATEGORY,
    UPPER(TRIM(NSFR_CATEGORY)) AS NSFR_CATEGORY,
    (CONCENTRATION_FLAG = 'Y') AS HAS_CONCENTRATION_RISK,
    (LARGE_DEPOSIT_FLAG = 'Y') AS IS_LARGE_DEPOSIT,
    (LIQUIDITY_VIOLATION_FLAG = 'Y') AS HAS_LIQUIDITY_VIOLATION,
    CASE WHEN TRY_TO_DATE(MATURITY_DATE) IS NOT NULL
         THEN DATEDIFF('day', EFFECTIVE_DATE, TRY_TO_DATE(MATURITY_DATE))
         ELSE NULL END AS DEPOSIT_TERM_DAYS,
    CASE WHEN BALANCE > 0
         THEN ROUND(UNINSURED_AMOUNT / BALANCE, 4)
         ELSE 0 END AS UNINSURED_RATIO
FROM deduped
WHERE _rn = 1;
