CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_TRANSACTION AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.TRANSACTION_FACT
    WHERE TRANSACTION_ID IS NOT NULL
)
SELECT
    TRIM(TRANSACTION_ID) AS TRANSACTION_ID,
    TRIM(ACCOUNT_ID) AS ACCOUNT_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRANSACTION_DATE,
    TRANSACTION_TIME,
    TO_TIMESTAMP(TRANSACTION_DATE || ' ' || TRANSACTION_TIME, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_TIMESTAMP,
    UPPER(TRIM(TRANSACTION_TYPE)) AS TRANSACTION_TYPE,
    COALESCE(AMOUNT, 0) AS AMOUNT,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    UPPER(TRIM(DIRECTION)) AS DIRECTION,
    UPPER(TRIM(CHANNEL)) AS CHANNEL,
    TRIM(ORIGINATOR_NAME) AS ORIGINATOR_NAME,
    UPPER(TRIM(ORIGINATOR_COUNTRY)) AS ORIGINATOR_COUNTRY,
    TRIM(BENEFICIARY_NAME) AS BENEFICIARY_NAME,
    UPPER(TRIM(BENEFICIARY_COUNTRY)) AS BENEFICIARY_COUNTRY,
    TRIM(BENEFICIARY_BANK) AS BENEFICIARY_BANK,
    UPPER(TRIM(PURPOSE_CODE)) AS PURPOSE_CODE,
    (AML_FLAG = 'Y') AS HAS_AML_FLAG,
    UPPER(TRIM(AML_ALERT_TYPE)) AS AML_ALERT_TYPE,
    COALESCE(RISK_SCORE, 0) AS RISK_SCORE,
    UPPER(TRIM(SCREENING_STATUS)) AS SCREENING_STATUS,
    (IS_CASH = 'Y') AS IS_CASH,
    (CTR_FILED = 'Y') AS IS_CTR_FILED,
    (ORIGINATOR_COUNTRY != BENEFICIARY_COUNTRY) AS IS_CROSS_BORDER,
    CASE WHEN AMOUNT >= 10000 THEN TRUE ELSE FALSE END AS IS_LARGE_TRANSACTION
FROM deduped
WHERE _rn = 1;
