CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_PEP AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY PEP_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.PEP_LIST
    WHERE PEP_ID IS NOT NULL
)
SELECT
    TRIM(PEP_ID) AS PEP_ID,
    TRIM(FULL_NAME) AS FULL_NAME,
    UPPER(TRIM(POSITION)) AS POSITION,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    UPPER(TRIM(PEP_TIER)) AS PEP_TIER,
    UPPER(TRIM(RELATIONSHIP_TYPE)) AS RELATIONSHIP_TYPE,
    DATE_ADDED,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPPER(TRIM(SOURCE)) AS SOURCE,
    DATEDIFF('day', DATE_ADDED, CURRENT_DATE()) AS DAYS_ON_LIST
FROM deduped
WHERE _rn = 1;
