CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_SANCTIONS AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY WATCHLIST_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.SANCTIONS_WATCHLIST
    WHERE WATCHLIST_ID IS NOT NULL
)
SELECT
    TRIM(WATCHLIST_ID) AS WATCHLIST_ID,
    TRIM(ENTITY_NAME) AS ENTITY_NAME,
    UPPER(TRIM(ENTITY_TYPE)) AS ENTITY_TYPE,
    UPPER(TRIM(SOURCE_LIST)) AS SOURCE_LIST,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    DATE_LISTED,
    TRIM(REASON) AS REASON,
    UPPER(TRIM(STATUS)) AS STATUS,
    MATCH_SCORE_THRESHOLD,
    DATEDIFF('day', DATE_LISTED, CURRENT_DATE()) AS DAYS_ON_LIST
FROM deduped
WHERE _rn = 1;
