CREATE OR REPLACE VIEW RISK_DB.CURATED.INT_LOAN AS
WITH deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY LOAN_ID ORDER BY _LOADED_AT DESC) AS _rn
    FROM RISK_DB.RAW.LOAN_MASTER
    WHERE LOAN_ID IS NOT NULL
)
SELECT
    TRIM(LOAN_ID) AS LOAN_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(ACCOUNT_ID) AS ACCOUNT_ID,
    UPPER(TRIM(LOAN_TYPE)) AS LOAN_TYPE,
    COALESCE(LOAN_AMOUNT, 0) AS LOAN_AMOUNT,
    COALESCE(OUTSTANDING_BALANCE, 0) AS OUTSTANDING_BALANCE,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    INTEREST_RATE,
    ORIGINATION_DATE,
    MATURITY_DATE,
    UPPER(TRIM(COLLATERAL_TYPE)) AS COLLATERAL_TYPE,
    COALESCE(COLLATERAL_VALUE, 0) AS COLLATERAL_VALUE,
    LTV_RATIO,
    UPPER(TRIM(INTERNAL_RATING)) AS INTERNAL_RATING,
    PD,
    LGD,
    EAD,
    RISK_WEIGHT_PCT,
    COALESCE(RWA, 0) AS RWA,
    COALESCE(EXPECTED_LOSS, 0) AS EXPECTED_LOSS,
    COALESCE(CAPITAL_REQUIREMENT, 0) AS CAPITAL_REQUIREMENT,
    UPPER(TRIM(BASEL_APPROACH)) AS BASEL_APPROACH,
    UPPER(TRIM(ASSET_CLASS)) AS ASSET_CLASS,
    UPPER(TRIM(STATUS)) AS STATUS,
    (BASEL_VIOLATION_FLAG = 'Y') AS HAS_BASEL_VIOLATION,
    (COLLATERAL_TYPE IS NOT NULL) AS IS_SECURED,
    DATEDIFF('month', ORIGINATION_DATE, MATURITY_DATE) AS LOAN_TERM_MONTHS,
    DATEDIFF('month', CURRENT_DATE(), MATURITY_DATE) AS MONTHS_TO_MATURITY
FROM deduped
WHERE _rn = 1;
