CREATE OR REPLACE PROCEDURE RISK_DB.RAW.SP_LOAD_RAW_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
BEGIN
  -- Load CUSTOMER_MASTER
  COPY INTO RISK_DB.RAW.CUSTOMER_MASTER (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, DATE_OF_BIRTH,
    NATIONALITY, COUNTRY_OF_RESIDENCE, CUSTOMER_TYPE, INDUSTRY, RISK_RATING,
    KYC_STATUS, KYC_LAST_REVIEWED, ONBOARDING_DATE, PEP_FLAG, SANCTIONS_MATCH_FLAG,
    ANNUAL_INCOME, SOURCE_OF_FUNDS, ACCOUNT_PURPOSE, STATUS,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*CUSTOMER_MASTER[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load ACCOUNT_MASTER
  COPY INTO RISK_DB.RAW.ACCOUNT_MASTER (
    ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, CURRENCY, OPENING_DATE,
    STATUS, BRANCH_CODE, COUNTRY, BALANCE, CREDIT_LIMIT,
    OVERDRAFT_LIMIT, LAST_ACTIVITY_DATE, RISK_SCORE,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*ACCOUNT_MASTER[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load LOAN_MASTER
  COPY INTO RISK_DB.RAW.LOAN_MASTER (
    LOAN_ID, CUSTOMER_ID, ACCOUNT_ID, LOAN_TYPE, LOAN_AMOUNT,
    OUTSTANDING_BALANCE, CURRENCY, INTEREST_RATE, ORIGINATION_DATE, MATURITY_DATE,
    COLLATERAL_TYPE, COLLATERAL_VALUE, LTV_RATIO, INTERNAL_RATING, PD,
    LGD, EAD, RISK_WEIGHT_PCT, RWA, EXPECTED_LOSS,
    CAPITAL_REQUIREMENT, BASEL_APPROACH, ASSET_CLASS, STATUS, BASEL_VIOLATION_FLAG,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
           $16,$17,$18,$19,$20,$21,$22,$23,$24,$25,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*LOAN_MASTER[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load LOAN_PERFORMANCE
  COPY INTO RISK_DB.RAW.LOAN_PERFORMANCE (
    PERFORMANCE_ID, LOAN_ID, CUSTOMER_ID, REPORT_DATE, DAYS_PAST_DUE,
    DELINQUENCY_STATUS, PAYMENT_AMOUNT_DUE, PAYMENT_AMOUNT_RECEIVED, OUTSTANDING_PRINCIPAL, ACCRUED_INTEREST,
    PROVISION_AMOUNT, STAGE_IFRS9, ECL_AMOUNT, RESTRUCTURED_FLAG, WRITE_OFF_FLAG,
    RECOVERY_AMOUNT, RISK_MIGRATION,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*LOAN_PERFORMANCE[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load TRANSACTION_FACT
  COPY INTO RISK_DB.RAW.TRANSACTION_FACT (
    TRANSACTION_ID, ACCOUNT_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME,
    TRANSACTION_TYPE, AMOUNT, CURRENCY, DIRECTION, CHANNEL,
    ORIGINATOR_NAME, ORIGINATOR_COUNTRY, BENEFICIARY_NAME, BENEFICIARY_COUNTRY, BENEFICIARY_BANK,
    PURPOSE_CODE, AML_FLAG, AML_ALERT_TYPE, RISK_SCORE, SCREENING_STATUS,
    IS_CASH, CTR_FILED,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*TRANSACTION_FACT[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load DEPOSIT_BALANCES
  COPY INTO RISK_DB.RAW.DEPOSIT_BALANCES (
    DEPOSIT_ID, ACCOUNT_ID, CUSTOMER_ID, DEPOSIT_TYPE, BALANCE,
    CURRENCY, EFFECTIVE_DATE, MATURITY_DATE, INTEREST_RATE, INSURED_AMOUNT,
    UNINSURED_AMOUNT, STABILITY_FACTOR, RUN_OFF_FACTOR, LCR_CATEGORY, NSFR_CATEGORY,
    CONCENTRATION_FLAG, LARGE_DEPOSIT_FLAG, LIQUIDITY_VIOLATION_FLAG,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*DEPOSIT_BALANCES[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load PEP_LIST
  COPY INTO RISK_DB.RAW.PEP_LIST (
    PEP_ID, FULL_NAME, POSITION, COUNTRY, PEP_TIER,
    RELATIONSHIP_TYPE, DATE_ADDED, STATUS, SOURCE,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*PEP_LIST[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Load SANCTIONS_WATCHLIST
  COPY INTO RISK_DB.RAW.SANCTIONS_WATCHLIST (
    WATCHLIST_ID, ENTITY_NAME, ENTITY_TYPE, SOURCE_LIST, COUNTRY,
    DATE_LISTED, REASON, STATUS, MATCH_SCORE_THRESHOLD,
    _SOURCE_FILE, _LOADED_AT
  )
  FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
  )
  FILE_FORMAT = 'RISK_DB.RAW.CSV_FORMAT'
  PATTERN = '.*SANCTIONS_WATCHLIST[.]csv'
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE;

  -- Parse PDF policy documents from POLICIES_STAGE and load into POLICY_DOCUMENTS
  INSERT INTO RISK_DB.RAW.POLICY_DOCUMENTS (POLICY_NAME, CLASSIFICATION, GENERATED_DATE, PURPOSE, VIOLATIONS, FULL_CONTENT, _SOURCE_FILE, _LOADED_AT)
  SELECT
      REPLACE(SPLIT_PART(relative_path, '/', -1), '.pdf', '') AS POLICY_NAME,
      TRIM(REGEXP_SUBSTR(parsed_content, 'Classification: ([A-Z]+)', 1, 1, 'e')) AS CLASSIFICATION,
      TRIM(REGEXP_SUBSTR(parsed_content, 'Generated: ([0-9_]+)', 1, 1, 'e')) AS GENERATED_DATE,
      TRIM(SUBSTR(parsed_content,
          POSITION('## Purpose' IN parsed_content) + 11,
          POSITION('##' IN SUBSTR(parsed_content, POSITION('## Purpose' IN parsed_content) + 11)) - 1
      )) AS PURPOSE,
      CASE WHEN POSITION('## Violations' IN parsed_content) > 0
           THEN TRIM(SUBSTR(parsed_content, POSITION('## Violations' IN parsed_content) + 14))
           ELSE NULL
      END AS VIOLATIONS,
      parsed_content AS FULL_CONTENT,
      relative_path AS _SOURCE_FILE,
      CURRENT_TIMESTAMP() AS _LOADED_AT
  FROM (
      SELECT
          relative_path,
          AI_PARSE_DOCUMENT(
              TO_FILE('@RISK_DB.RAW.POLICIES_STAGE', relative_path),
              {'mode': 'LAYOUT'}
          ):content::STRING AS parsed_content
      FROM DIRECTORY(@RISK_DB.RAW.POLICIES_STAGE)
      WHERE relative_path ILIKE '%.pdf'
        AND relative_path LIKE '%/%'
        AND relative_path NOT LIKE '%/%/%'
  )
  WHERE NOT EXISTS (
      SELECT 1 FROM RISK_DB.RAW.POLICY_DOCUMENTS pd
      WHERE pd._SOURCE_FILE = relative_path
  );

  RETURN 'Raw data load completed successfully';
END;
$$;
