CREATE SEQUENCE IF NOT EXISTS RISK_DB.CURATED.SEQ_DIM_CUSTOMER START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS RISK_DB.CURATED.SEQ_DIM_ACCOUNT START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS RISK_DB.CURATED.SEQ_DIM_LOAN START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS RISK_DB.CURATED.SEQ_DIM_PEP START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS RISK_DB.CURATED.SEQ_DIM_SANCTIONS START = 1 INCREMENT = 1;
