CREATE TABLE IF NOT EXISTS RISK_DB.CURATED.DIM_DATE AS
WITH date_spine AS (
    SELECT DATEADD('day', SEQ4(), '2023-01-01'::DATE) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 1461))
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_SK,
    DATE_VALUE AS FULL_DATE,
    YEAR(DATE_VALUE) AS YEAR,
    QUARTER(DATE_VALUE) AS QUARTER,
    MONTH(DATE_VALUE) AS MONTH,
    DAYOFMONTH(DATE_VALUE) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_VALUE) AS DAY_OF_WEEK,
    DAYOFYEAR(DATE_VALUE) AS DAY_OF_YEAR,
    WEEKOFYEAR(DATE_VALUE) AS WEEK_OF_YEAR,
    TO_CHAR(DATE_VALUE, 'YYYY-Q') AS YEAR_QUARTER,
    TO_CHAR(DATE_VALUE, 'YYYY-MM') AS YEAR_MONTH,
    DECODE(DAYOFWEEK(DATE_VALUE), 0, 'Sunday', 1, 'Monday', 2, 'Tuesday', 3, 'Wednesday', 4, 'Thursday', 5, 'Friday', 6, 'Saturday') AS DAY_NAME,
    DECODE(MONTH(DATE_VALUE), 1,'January',2,'February',3,'March',4,'April',5,'May',6,'June',7,'July',8,'August',9,'September',10,'October',11,'November',12,'December') AS MONTH_NAME,
    CASE WHEN DAYOFWEEK(DATE_VALUE) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    CASE WHEN DAYOFWEEK(DATE_VALUE) IN (1,2,3,4,5) THEN TRUE ELSE FALSE END AS IS_WEEKDAY,
    CASE WHEN DAYOFMONTH(DATE_VALUE) = 1 THEN TRUE ELSE FALSE END AS IS_MONTH_START,
    CASE WHEN DATE_VALUE = LAST_DAY(DATE_VALUE) THEN TRUE ELSE FALSE END AS IS_MONTH_END,
    CASE WHEN MONTH(DATE_VALUE) = 1 AND DAYOFMONTH(DATE_VALUE) = 1 THEN TRUE ELSE FALSE END AS IS_YEAR_START,
    CASE WHEN MONTH(DATE_VALUE) = 12 AND DAYOFMONTH(DATE_VALUE) = 31 THEN TRUE ELSE FALSE END AS IS_YEAR_END,
    LAST_DAY(DATE_VALUE) AS MONTH_END_DATE,
    DATE_TRUNC('week', DATE_VALUE) AS WEEK_START_DATE,
    DATEDIFF('day', DATE_TRUNC('quarter', DATE_VALUE), DATE_VALUE) + 1 AS DAY_OF_QUARTER
FROM date_spine;
