CREATE TABLE IF NOT EXISTS RISK_DB.CURATED.DIM_PEP (
    DIM_PEP_SK NUMBER DEFAULT RISK_DB.CURATED.SEQ_DIM_PEP.NEXTVAL,
    PEP_ID TEXT,
    FULL_NAME TEXT,
    POSITION TEXT,
    COUNTRY TEXT,
    PEP_TIER TEXT,
    RELATIONSHIP_TYPE TEXT,
    DATE_ADDED DATE,
    STATUS TEXT,
    SOURCE TEXT,
    DAYS_ON_LIST NUMBER,
    EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    RECORD_HASH TEXT
);
