CREATE TABLE IF NOT EXISTS RISK_DB.CURATED.DIM_SANCTIONS (
    DIM_SANCTIONS_SK NUMBER DEFAULT RISK_DB.CURATED.SEQ_DIM_SANCTIONS.NEXTVAL,
    WATCHLIST_ID TEXT,
    ENTITY_NAME TEXT,
    ENTITY_TYPE TEXT,
    SOURCE_LIST TEXT,
    COUNTRY TEXT,
    DATE_LISTED DATE,
    REASON TEXT,
    STATUS TEXT,
    MATCH_SCORE_THRESHOLD NUMBER,
    DAYS_ON_LIST NUMBER,
    EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    RECORD_HASH TEXT
);
