CREATE TABLE IF NOT EXISTS RISK_DB.CURATED.REF_POLICY_DOCUMENTS (
    POLICY_ID NUMBER,
    POLICY_NAME TEXT,
    CLASSIFICATION TEXT,
    GENERATED_AT TIMESTAMP_NTZ,
    PURPOSE TEXT,
    VIOLATIONS TEXT,
    FULL_CONTENT TEXT,
    CONTENT_LENGTH_CHARS NUMBER,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
