CREATE TABLE IF NOT EXISTS RISK_DB.RAW.POLICY_DOCUMENTS (
  POLICY_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  POLICY_NAME VARCHAR,
  CLASSIFICATION VARCHAR,
  GENERATED_DATE VARCHAR,
  PURPOSE VARCHAR,
  VIOLATIONS VARCHAR,
  FULL_CONTENT VARCHAR,
  _SOURCE_FILE VARCHAR,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
