CREATE TABLE IF NOT EXISTS RISK_DB.RAW.PEP_LIST (
  PEP_ID STRING,
  FULL_NAME STRING,
  POSITION STRING,
  COUNTRY STRING,
  PEP_TIER STRING,
  RELATIONSHIP_TYPE STRING,
  DATE_ADDED DATE,
  STATUS STRING,
  SOURCE STRING,
  _SOURCE_FILE STRING,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
