CREATE TABLE IF NOT EXISTS RISK_DB.RAW.SANCTIONS_WATCHLIST (
  WATCHLIST_ID STRING,
  ENTITY_NAME STRING,
  ENTITY_TYPE STRING,
  SOURCE_LIST STRING,
  COUNTRY STRING,
  DATE_LISTED DATE,
  REASON STRING,
  STATUS STRING,
  MATCH_SCORE_THRESHOLD NUMBER(5,2),
  _SOURCE_FILE STRING,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
