CREATE TABLE IF NOT EXISTS RISK_DB.RAW.ACCOUNT_MASTER (
  ACCOUNT_ID STRING,
  CUSTOMER_ID STRING,
  ACCOUNT_TYPE STRING,
  CURRENCY STRING,
  OPENING_DATE DATE,
  STATUS STRING,
  BRANCH_CODE STRING,
  COUNTRY STRING,
  BALANCE NUMBER(18,2),
  CREDIT_LIMIT NUMBER(18,2),
  OVERDRAFT_LIMIT NUMBER(18,2),
  LAST_ACTIVITY_DATE DATE,
  RISK_SCORE NUMBER(5,2),
  _SOURCE_FILE STRING,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
