-- =============================================================================
-- Public (Streamlit Community Cloud) access for the Risk & Fraud Copilot app.
--
-- Creates a read-only service identity the hosted app connects as:
--   COPILOT_PUBLIC_WH   dedicated XSMALL warehouse, credit-capped
--   COPILOT_PUBLIC_RM   resource monitor: 10 credits/month, suspends at 100%
--   COPILOT_PUBLIC_ROLE read-only on CURATED + SEMANTICS, Cortex usage, no RAW
--   COPILOT_PUBLIC_SVC  TYPE=SERVICE user, key-pair auth only (no password)
--
-- Run as ACCOUNTADMIN. Set the public key separately (never commit keys):
--   ALTER USER COPILOT_PUBLIC_SVC SET RSA_PUBLIC_KEY = '<public key body>';
--
-- Teardown: DROP USER COPILOT_PUBLIC_SVC;  (cuts off the public app instantly)
-- =============================================================================
USE ROLE ACCOUNTADMIN;

-- Warehouse + cost cap ---------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS COPILOT_PUBLIC_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Public Streamlit Community Cloud app for the Risk & Fraud Copilot';

CREATE OR REPLACE RESOURCE MONITOR COPILOT_PUBLIC_RM
  WITH CREDIT_QUOTA = 10
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE COPILOT_PUBLIC_WH SET RESOURCE_MONITOR = COPILOT_PUBLIC_RM;

-- Read-only role -----------------------------------------------------------------
CREATE ROLE IF NOT EXISTS COPILOT_PUBLIC_ROLE
  COMMENT = 'Read-only access for the public Risk & Fraud Copilot app';

GRANT USAGE ON WAREHOUSE COPILOT_PUBLIC_WH TO ROLE COPILOT_PUBLIC_ROLE;
GRANT USAGE ON DATABASE RISK_DB TO ROLE COPILOT_PUBLIC_ROLE;
GRANT USAGE ON SCHEMA RISK_DB.CURATED TO ROLE COPILOT_PUBLIC_ROLE;
GRANT USAGE ON SCHEMA RISK_DB.SEMANTICS TO ROLE COPILOT_PUBLIC_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA RISK_DB.CURATED TO ROLE COPILOT_PUBLIC_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RISK_DB.CURATED TO ROLE COPILOT_PUBLIC_ROLE;

GRANT SELECT ON SEMANTIC VIEW RISK_DB.SEMANTICS.RISK_FRAUD_SIGNALS TO ROLE COPILOT_PUBLIC_ROLE;
GRANT SELECT ON SEMANTIC VIEW RISK_DB.SEMANTICS.REGULATORY_REPORTING TO ROLE COPILOT_PUBLIC_ROLE;
GRANT SELECT ON SEMANTIC VIEW RISK_DB.SEMANTICS.TRANSACTION_ACCOUNT_360 TO ROLE COPILOT_PUBLIC_ROLE;
GRANT SELECT ON SEMANTIC VIEW RISK_DB.SEMANTICS.INVESTIGATION_FACTS TO ROLE COPILOT_PUBLIC_ROLE;

GRANT USAGE ON CORTEX SEARCH SERVICE RISK_DB.SEMANTICS.POLICY_SEARCH TO ROLE COPILOT_PUBLIC_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COPILOT_PUBLIC_ROLE;

-- Service user (key-pair only) ---------------------------------------------------
CREATE USER IF NOT EXISTS COPILOT_PUBLIC_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = COPILOT_PUBLIC_ROLE
  DEFAULT_WAREHOUSE = COPILOT_PUBLIC_WH
  DEFAULT_NAMESPACE = RISK_DB.CURATED
  COMMENT = 'Service identity for the public Streamlit Community Cloud app';

GRANT ROLE COPILOT_PUBLIC_ROLE TO USER COPILOT_PUBLIC_SVC;
