CREATE STAGE IF NOT EXISTS RISK_DB.RAW.POLICIES_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Risk and compliance policy documents';

CREATE STAGE IF NOT EXISTS RISK_DB.RAW.RISK_FRAUD_DATA_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Banking risk sample data CSVs';
